[project]
name = "animationgenerationgsoc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "accelerate>=1.13.0",
    "numpy>=2.0.0",
    "opencv-python>=4.12.0",
    "pillow>=12.2.0",
    "pyrender>=0.1.45",
    "python-dotenv>=1.2.2",
    "rembg[gpu]>=2.0.75",
    "pymatting==1.1.15",
    "torch==2.6.0",
    "torchvision==0.21.0",
    "transformers>=5.9.0",
    "trimesh[easy]>=4.12.2",
    "pytorch3d==0.7.9",
    "bpy>=4.4.0",
    "open3d>=0.19.0",
    "pymeshlab>=2025.7.post1",
    "igraph>=1.0.0",
    "jaxtyping>=0.3.11",
    "triangle>=20250106",
    "scipy>=1.17.1",
]

[tool.setuptools]
packages = ["animgen"]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }

pytorch3d = [
    { url = "https://github.com/MiroPsota/torch_packages_builder/releases/download/pytorch3d-0.7.9/pytorch3d-0.7.9+pt2.6.0cu124-cp311-cp311-linux_x86_64.whl", marker = "python_version == '3.11'" },
    { url = "https://github.com/MiroPsota/torch_packages_builder/releases/download/pytorch3d-0.7.9/pytorch3d-0.7.9+pt2.6.0cu124-cp312-cp312-linux_x86_64.whl", marker = "python_version == '3.12'" },
    { url = "https://github.com/MiroPsota/torch_packages_builder/releases/download/pytorch3d-0.7.9/pytorch3d-0.7.9+pt2.6.0cu124-cp313-cp313-linux_x86_64.whl", marker = "python_version == '3.13'" }
]

[dependency-groups]
dev = [
    "beartype>=0.22.9",
    "ipykernel>=7.3.0",
    "pre-commit>=4.6.0",
    "pyright>=1.1.411",
    "pytest>=9.1.1",
    "pyvista>=0.48.4",
    "ruff>=0.15.20",
]

[tool.ruff]
exclude = [
    "experiments/",
    "demo",
]

[tool.pyright]
include = ["animgen"]
exclude = [
    "**/node_modules",
    "**/__pycache__",
    "**/.*",
    ".venv",
    "experiments/",
    "demo",
]
typeCheckingMode = "standard"
